[FE] KVK improvements
Centric-RO/Local4Local pull request #90
Opened 2024-12-04 15:21 UTC by dungurea-centric

2024-12-04 15:23 UTC, centric-aspirido requested changes

2024-12-04 15:23 UTC, centric-aspirido commented on frontend/src/app/components/merchant-dialog/merchant-dialog.component.ts
> +				requiredMessage: 'register.error.kvkNumberRequired'
Maybe we can rename this label to identifierNumberRequired because it will be different translation from country to country.

2024-12-04 15:23 UTC, centric-aspirido commented on frontend/src/app/components/merchant-dialog/merchant-dialog.component.ts
> +				requiredMessage: 'register.error.kvkNumberRequired'
Same for other places where kvk appears.

2024-12-05 08:45 UTC, centric-aspirido approved these changes

2024-12-05 09:41 UTC, rgramesc approved these changes

2024-12-05 11:00 UTC, merged